#!/bin/sh
set -e

ln -sf /opt/slideio-viewer/bin/slideio-viewer /usr/bin/slideio-viewer

mkdir -p /usr/share/applications /usr/share/icons/hicolor/256x256/apps
ln -sf /opt/slideio-viewer/share/applications/slideio-viewer.desktop \
       /usr/share/applications/slideio-viewer.desktop
ln -sf /opt/slideio-viewer/share/icons/hicolor/256x256/apps/slideio-viewer.png \
       /usr/share/icons/hicolor/256x256/apps/slideio-viewer.png

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications || true
fi
exit 0
